name: Test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Load super-linter env variables
        run: |
          cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  functional:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install altwalker-viewer
        run: |
          pip install -e .

      - name: Check altwalker-viewer version
        run:
          altwalker-viewer --version
