name: Test

on: push

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Load super-linter env variables
        run: |
          cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Lint Code Base
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pytest:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PyPi dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest

  functional:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install altwalker-viewer
        run: |
          pip install -e .

      - name: Check altwalker-viewer version
        run:
          altwalker-viewer --version
