name: Test

on: push

jobs:
  functional:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install altwalker-viewer
        run: |
          pip install -e .

      - name: Check altwalker-viewer version
        run:
          altwalker-viewer --version
